use_frameworks!
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ios' do

  # Pods for ios
  pod 'shared', :path => '../shared/'

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosUITests' do
    # Pods for testing
  end

end
